// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://krmcurjxccbkmoebumbn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtybWN1cmp4Y2Nia21vZWJ1bWJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NDI5NjEsImV4cCI6MjA2MzExODk2MX0.8nEwfEonPwv9TfIFvctq7F7toXAVXpAf8T4ixGSwwug";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);